import os
from dotenv import load_dotenv

load_dotenv()

LANGCHAIN_TRACING_V2 = False

SLACK_TOKEN = os.getenv("SLACK_TOKEN")
SLANT_API_KEY = os.getenv("SLANT_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
POSTGRES_ENGINE = os.getenv("POSTGRES_ENGINE")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
FLIPSIDE_API_KEY = os.getenv("FLIPSIDE_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")

TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN")
TWITTER_BEARER_TOKEN_NDS = os.getenv("TWITTER_BEARER_TOKEN_NDS")
TWITTER_BEARER_TOKEN_TRAILS = os.getenv("TWITTER_BEARER_TOKEN_TRAILS")
TWITTER_BEARER_TOKEN_ASH = os.getenv("TWITTER_BEARER_TOKEN_ASH")

# Configure AWS credentials
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')
AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME')

SOLANA_RPC_URL = os.getenv("SOLANA_RPC_URL")
ACTIVE_TWITTER_TOKENS = [TWITTER_BEARER_TOKEN_NDS]
